const config=window.MSB_CONFIG||{};const supabaseClient=window.supabase?window.supabase.createClient(config.url,config.anonKey):null;let allProducts=[],cart=JSON.parse(localStorage.getItem('mlb-cart')||'[]'),activeCat='all',query='';const WA='919876543210';
const photo=(key)=>window.MSB_PHOTOS?.[key]||'';
function money(n){return `₹${Number(n||0).toLocaleString('en-IN')}`}
function esc(s){const d=document.createElement('div');d.textContent=s??'';return d.innerHTML}
function sync(){localStorage.setItem('mlb-cart',JSON.stringify(cart));document.getElementById('cartCount').textContent=cart.length;let total=cart.reduce((a,x)=>a+Number(x.price||0),0);document.getElementById('cartSubtotal').textContent=money(total)}
function renderCart(){const box=document.getElementById('cartItemsContainer');if(!cart.length){box.innerHTML='<div class="empty-cart"><div>♡</div><h4>Your basket is waiting.</h4><p>Add a little something sweet.</p></div>';sync();return}box.innerHTML=cart.map((x,i)=>`<div class="cart-line"><div><strong>${esc(x.name)}</strong><small>${esc(x.details||'Freshly baked to order')}</small><b>${money(x.price)}</b></div><button data-remove="${i}" aria-label="Remove ${esc(x.name)}">Remove</button></div>`).join('');sync()}
function openCart(){renderCart();document.getElementById('cartDrawer').classList.add('active');document.getElementById('cartOverlay').classList.add('active')}
function closeCart(){document.getElementById('cartDrawer').classList.remove('active');document.getElementById('cartOverlay').classList.remove('active')}
function renderProducts(){const grid=document.getElementById('productGrid');let list=activeCat==='all'?allProducts:allProducts.filter(p=>(p.category||'').toLowerCase()===activeCat.toLowerCase());if(query)list=list.filter(p=>`${p.name} ${p.description} ${p.category}`.toLowerCase().includes(query.toLowerCase()));if(!list.length){grid.innerHTML='<div class="empty-cart"><h4>Nothing here yet.</h4><p>Try another category or search.</p></div>';return}grid.innerHTML=list.map((p,i)=>{const src=p.photo_url||((i%2===0)?photo('chocolate-hazelnut-cake'):photo('berry-cheesecake'));return `<article class="product-card" data-id="${esc(p.id)}"><div class="product-thumb">${src?`<img src="${esc(src)}" alt="${esc(p.name)}" loading="lazy">`:'<div class="photo-fallback">✦</div>'}<span class="product-tag">${esc(p.category||'Fresh bake')}</span></div><div class="product-details"><h3 class="product-title">${esc(p.name||'Fresh bake')}</h3><p class="product-desc">${esc(p.description||'Handmade and freshly prepared to order.')}</p><div class="product-footer"><span class="product-price">${money(p.price)}</span><button class="add-btn" data-add="${esc(p.id)}">Add +</button></div></div></article>`}).join('')}
async function fetchProducts(){const grid=document.getElementById('productGrid');if(!supabaseClient){grid.innerHTML='<div class="empty-cart"><h4>Menu connection unavailable.</h4></div>';return}const {data,error}=await supabaseClient.from('products').select('*').eq('is_available',true).order('created_at',{ascending:false});if(error){console.error(error);grid.innerHTML='<div class="empty-cart"><h4>We are refreshing the menu.</h4><p>Please try again in a moment.</p></div>';return}allProducts=data||[];renderProducts()}
function productById(id){return allProducts.find(p=>String(p.id)===String(id))}
function addProduct(id){const p=productById(id);if(!p)return;cart.push({id:p.id,name:p.name,price:Number(p.price),details:p.category||''});openCart()}
function openProduct(p){const src=p.photo_url||photo('chocolate-hazelnut-cake');document.getElementById('productModalContent').innerHTML=`<div class="modal-photo">${src?`<img src="${esc(src)}" alt="${esc(p.name)}">`:''}</div><div class="modal-info"><div class="eyebrow">${esc(p.category||'Fresh bake')}</div><h2>${esc(p.name)}</h2><p>${esc(p.description||'Handmade and freshly prepared to order.')}</p><div class="modal-price">${money(p.price)}</div><button class="btn primary" data-modal-add="${esc(p.id)}">Add to bag +</button></div>`;document.getElementById('productModal').classList.add('active')}
function closeProduct(){document.getElementById('productModal').classList.remove('active')}
function initBuilder(){const flavor=document.getElementById('buildFlavor'),msg=document.getElementById('buildMessage'),price=document.getElementById('customTotalPrice'),preview=document.getElementById('previewMessageText'),caption=document.getElementById('previewFlavor');function update(){const o=flavor.options[flavor.selectedIndex],size=document.querySelector('input[name="buildSize"]:checked'),total=Math.round(Number(o.dataset.price)*Number(size.dataset.multiplier));price.textContent=money(total);preview.textContent=msg.value.trim()||'Happy Birthday!';caption.textContent=`${o.value} · ${size.value}`;document.querySelector('.tier.base').style.height=size.value==='2 kg'?'130px':size.value==='1 kg'?'115px':'95px'}flavor.addEventListener('change',update);msg.addEventListener('input',update);document.querySelectorAll('input[name="buildSize"]').forEach(x=>x.addEventListener('change',update));document.getElementById('addCustomToCartBtn').onclick=()=>{const o=flavor.options[flavor.selectedIndex],size=document.querySelector('input[name="buildSize"]:checked');cart.push({id:`custom-${Date.now()}`,name:`Custom Cake · ${o.value}`,price:Math.round(Number(o.dataset.price)*Number(size.dataset.multiplier)),details:`${size.value}${msg.value.trim()?` · “${msg.value.trim()}”`:''}`});openCart()};update()}
function customRequest(){document.getElementById('studio').scrollIntoView({behavior:'smooth'});setTimeout(()=>document.getElementById('buildMessage').focus(),500)}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){e.stopPropagation();addProduct(add.dataset.add);return}const card=e.target.closest('.product-card');if(card&& !e.target.closest('button')){const p=productById(card.dataset.id);if(p)openProduct(p)}const rem=e.target.closest('[data-remove]');if(rem){cart.splice(Number(rem.dataset.remove),1);renderCart()}const modalAdd=e.target.closest('[data-modal-add]');if(modalAdd){addProduct(modalAdd.dataset.modalAdd);closeProduct()}});
document.getElementById('categoryTabs').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;document.querySelectorAll('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeCat=b.dataset.cat;renderProducts()});document.getElementById('searchInput').addEventListener('input',e=>{query=e.target.value;renderProducts()});document.getElementById('cartBtn').onclick=openCart;document.getElementById('closeCart').onclick=closeCart;document.getElementById('cartOverlay').onclick=closeCart;document.getElementById('closeProduct').onclick=closeProduct;document.getElementById('productModal').addEventListener('click',e=>{if(e.target.id==='productModal')closeProduct()});document.getElementById('heroCustom').onclick=customRequest;document.getElementById('ctaCustom').onclick=customRequest;
document.getElementById('whatsappCheckoutBtn').onclick=()=>{if(!cart.length)return;let total=cart.reduce((a,x)=>a+Number(x.price),0);let text='Hi Ms. Lil Baker! 🧁\nI would like to order:\n\n'+cart.map((x,i)=>`${i+1}. ${x.name} — ${money(x.price)}${x.details?` (${x.details})`:''}`).join('\n')+`\n\nTotal: ${money(total)}\nPlease confirm availability!`;window.open(`https://wa.me/${WA}?text=${encodeURIComponent(text)}`,'_blank')};
document.addEventListener('DOMContentLoaded',()=>{const hp=document.getElementById('heroPhoto'),sp=document.getElementById('storyPhoto');const a=photo('chocolate-hazelnut-cake'),b=photo('berry-cheesecake');if(hp&&a)hp.src=a;if(sp&&b)sp.src=b;initBuilder();renderCart();fetchProducts()});
